server:
  port: 8082

spring:
  application:
    name: spring-data-jpa-hibernate

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/illustrator_db?currentSchema=illustrator
    username: postgres
    password: password

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: always